server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://42.193.109.34:3306/hospitalized?useUnicode=true&characterEncoding=utf-8&serverTimeZone=Asia/Shanghai

    username: root
    password: jfh681521
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  redis:
    host: 42.193.109.34
    port: 6800

# 民族对应的字典码
dict:
  code:
    nation: '001'
    logtype: '002'

# jwt 秘钥和登陆过期时间
bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000

# 重置密码
init:
  passwd: 123456

#哈希缓存
redis:
  hashkey: project
